### ISSUE TITLE
Mob Damage Multiplier Doesn't Work

### ISSUE THREAD

**Issue by Eowomir7** [SilentChaos512/ScalingHealth#100]
### Versions

Minecraft Version: 1.12.2(multiple forge versions tested)
Scaling Health Version: 1.3.14
Silent Lib Version: 2.2.18

### Expected behavior

- mob damage multiplier increasing mobs damage per difficulty level

### Actual behaviour

- mob at all difficulty levels hitting for the same amount

### Steps to reproduce the problem

1. run the mod
2. teleport to high difficulty levels
3. all mobs except blights hitting for vanilla damage
4. Doesn't matter if i change the multiplier in the config
5. Doesn't matter what forge version i use for 1.12.2
6. tested with no other mods running

**Comment by SilentChaos512** [comment]
Mind sharing your config file? I still see normal results, with zombies dealing 3 damage at zero difficulty and anywhere from 3.5~10+ at 250.

**Comment by Eowomir7** [comment]
ok here it is
[scalinghealth.zip](https://github.com/SilentChaos512/ScalingHealth/files/1935211/scalinghealth.zip)

**Comment by SilentChaos512** [comment]
Reproduced with your main.cfg. Must be something specific to distance-based difficulty.

(edit) No, it's because the mobs are receiving so much extra health. There's no difficulty left to add damage from after health is added. I need to take the health multipliers into account.

**Comment by Eowomir7** [comment]
now I'm wondering how you went about it, i figured it would just add both multipliers per difficulty. is there a limit to the difficulty multipliers? the reason i have thee hp increase set so high is because we intend to use enhancement mods for damage and defense i was originally testing to include this levelup mod(skill trees for defense and offense increases) and weaponlevels mod(increases base damage for swords and goes up based on rarity and weapon level). depending on some of the stat boosts i can hit anywhere from 20-700 damage from a swing by combining those 2 mods and certain abilities/stat increases. but with the damage multiplier as is the enemies cant even damage me, but it takes me forever to kill the dudes. ill probably be reducing the hp increase numbers to 2-3 depending on how the damage multiplier turns out. i was hoping for like a 20% or 30%(0.2 or 0.3)damage increase, or possibly a flat damage increase of 0.5 to 1 per level.

**Comment by SilentChaos512** [comment]
The math is a bit weird, I tried to leave Difficult Life's formula alone as much as possible (this mod started as an unofficial port of Difficult Life). It's something like this:
1. A difficulty value is calculated.
2. A health value is calculated (multiplier * difficulty + a random value).
3. The health value is _subtracted_ from the difficulty.
4. A damage value is calculated based on the _remaining difficulty_ (multiplier * difficulty + a random value).
5. The damage value is subtracted from the difficulty and the remainder is used for potion effects.

Not sure if some change I made created this bug/effect, or if it was always like that. DL had far fewer config options, so it might be because I added options for values that were designed to be constants.

At this point, I'm starting to think I should rewrite the whole function. I mention what Difficult Life did, but Scaling Health has evolved into it's own mod. No need to replicate it as closely as possible. Either way, I'll find a fix.

**Comment by Eowomir7** [comment]
Oh that makes sense then. Since some of these mobs are turning out with 500 to 1500 hp. So with my config it's doing 250 - 500 which of course would be negative so it's defaulting at 0 increase after subtracting the health multiplier...if it were me I would just remove the subtraction of the difficulty portion. It would be simple. Just have to edit 2 lines of code. But of course. Thats my opinion, It's your mod. Do what you feel is right. I'll be happy with whatever you choose to do as long as I can have epic battles with zombies end game. =)

**Comment by SilentChaos512** [comment]
Removed the subtractions of difficulty for now. Haven't tested it much, but entities are gaining lots of extra damage now using your config. Hopefully that won't impact default configs much, but I'll worry about that later. New version will be uploaded in a few hours, got a couple other things I'm working on.
