### ISSUE TITLE
Game stops responding the log says it's because of ScalingHealth!

### ISSUE THREAD

**Issue by Qattos** [SilentChaos512/ScalingHealth#204]
### Versions

- **Scaling Health**: 1.3.42+147
- **Silent Lib**: 3.0.13+167
- **Forge**: 14.23.5.2847
- **Modpack** (if applicable): RLCraft

### Expected behavior
Didn't understand what I should put here but I'd expect my game not to crash, actually it stopped responding and I killed it.

### Actual behaviour
- I was clearing a Doomlike Dungeon and fighting mobs then while getting hit by multiple mobs at the same time the game just stopped responding, I remember this happening to me with an older version of your mod and when I removed it the game worked fine.
- I have to add that this might have happened because I was hitting multiple mobs so quickly in a short period of time.

### Links/Images

- https://pastebin.com/aZmf4Pas

### Steps to reproduce the problem

This is rare, so there's no guaranteed way of reproducing it.
Was fighting mobs for over 10 minutes, one-shot-ing most of the mobs except the blighted/infernal mobs, then suddenly without any warning the game stopped responding and this coincided with me getting hit by multiple mobs at the same time and me hitting multiple mobs quickly with a sword that has an enchantment similar to lifesteal/vampirism that restores health according to the damage dealt to mobs.

**Comment by davidalb97** [comment]
Same problem.

### Versions
* Scaling Health: 1.3.42+147
* Silent Lib: 3.0.14+168
* Forge: 14.23.5.2854
* Modpack (if applicable): (Custom modpack)

#### Aditional Versions:
* MC: 1.12.2
* Roguelike Dungeons Fnar Edition: 2.1.4
* Doomlike Dungeons: 1.13.2
* Dungeon Mobs: 5.8.6
* Lycanites Mobs: 2.0.7.2
* Journey Map: 5.7.1

### Expected behavior
Game still working after using JourneyMap's World Map for a while.

### Actual behaviour
Game not working after using JourneyMap's World Map for a while.

### Links/Images
* https://pastebin.com/5nAQU9Wy

### Steps to reproduce the problem
Use lycanite mobs with default settings (default mob events config).
Use JourneyMap.
Create single player world in creative, go to World Map view in JourneyMap.
Wait for each lycanite mobs' event to spawn multiple mobs, accumulating over time (these mobs won't despawn).

### Notes
I think the cause was mob overpopulation with LycaniteMobs mob spawning events.
Scaling health itself may not be the cause for unresponsiveness, but the error still occurs.
