### ISSUE TITLE
[1.14.4] Power crystals

### ISSUE THREAD

**Issue by Qsandas** [SilentChaos512/ScalingHealth#245]
ScalingHealth-1.14.4-2.5.0+47
SilentLib-1.14.4-4.4.0+44
Forge 28.2.3

Expected Behavior

Use Power Crystal, lose configured amount of EXP, gain 0.5 hearts damage, crystal disappears.

## Actual Behavior

Used Power Crystal, nothing happens. If I'm below the required levels, it still gives the text of needing a certain amount to use it. If not, no message. The only thing disabled is the ore gen and the only thing changed otherwise was I set the level requirement.

**Comment by Cyborgmas** [comment]
So you want crystals to only be available as loot right?

Try re enabling the ore gen maybe, make sure that power crystals in game settings actually give damage (make the value not 0, by default it should not be though). 
Make sure you are not past the max damage increase, the default might be no max value though.
After that, try putting the damage increase at 1 (or more) instead of 0.5.

**Comment by Qsandas** [comment]
Tried all of it. Nothing. Even tried to see if opening to LAN would work, but no dice. This is no huge loss on my part, as I don't play on servers and a lot of my mods have very overpowered end-game items, But a bug is still a bug.

**Comment by Cyborgmas** [comment]
yup, thanks, ill check that
