### ISSUE TITLE
Health Scaling Modes?

### ISSUE THREAD

**Issue by SilentChaos512** [SilentChaos512/ScalingHealth#26]
Could be interesting to have modes that modify player health over time, similar to what's already done with difficulty. One suggestion (via Curse) was to scale with player XP:
> scalable with player xp level?   , say for instance maybe start the player with 100 hearts and then decrease the hearts by 1/2 heart per player xp level ? or maybe the other way around increasing the health 1/2 per player xp level?

Directly scaling the health like that may not work well, but a XP-based difficulty mode would be nice to have.

**Comment by Winddbourne** [comment]
I was just going to suggest an XP based health idea myself so I figure I'll put it here with SilentChaos512's suggestion. 

A lot of mods make both death and XP fairly trivial. Gravestone and tinkers construct are two that immediately come to mind. 

I think we could make death more significant if we set things up so that using heart canisters costs experience. This would be especially telling if you also lost your extra hearts on death.  This would mean that you really have a vested interest in staying alive. You may regain your items, you might grab back a portion of your XP . . . but you'll have to work hard to regain your lost health.

**Comment by SilentChaos512** [comment]
Already implemented, see #119.
