### ISSUE TITLE
Player health increase when die

### ISSUE THREAD

**Issue by momosundeass** [SilentChaos512/ScalingHealth#268]
ScalingHealth-1.15.2-3.0.5+52
SilentLib-1.15.2-4.6.1+49
forge-1.15.2-31.1.77

Optifine + Optiforge
OptiFine_1.15.2_HD_U_G1_pre15_MOD
OptiForge-MC1.15.2-0.1.17

## Another mod
Cyclic-1.15.2-0.4.1
- cyclic heart item was disabled in config

## Expected Behavior
after use Heart Crystal get 1 heart
and when player die player heart shouldn't increase

## Actual Behavior
after use Heart Crystal get 1 heart
and when player die player heart will increased

## Steps to Reproduce the Problem
1.new world (10 heart)
2.use 1 Heart Crystal to get 1 heart (11 heart)
3.die
4.observe health have increased by 1 heart (12 heart)

**Comment by Cyborgmas** [comment]
could you try without optifine/optiforge please? also use a paste site to give me the latest.log in your logs folder once you do that.

**Comment by momosundeass** [comment]
https://pastebin.com/HHwvkMzP
I remove optifine optiforge 
but issue still exist

**Comment by momosundeass** [comment]
I downgrade version of cyclic mod to version 
Cyclic-1.15.2-0.3.4
the issue don't seem to happen anymore

**Comment by Cyborgmas** [comment]
Okay super, could you then report the bug on cyclic's page as well and reference this issue? To see if they have an idea what could be causing this.

**Comment by FireController1847** [comment]
Hey, @Cyborgmas. I'm the developer of a mod called LevelHearts, and I have an issue with a very similar report to this. I was poking through their code noticing they use a very non-standard way of modifying the player's health. In fact, I just noticed that they modify the BASE VALUE of the health modifier, instead of using their own modifier. This is an issue on Cylic's end.

**Comment by Cyborgmas** [comment]
Thanks for letting me know and the in depth reporting!
