### ISSUE TITLE
Game crashes whenever a creeper explodes

### ISSUE THREAD

**Issue by Cyphrx** [SilentChaos512/ScalingHealth#287]
## Versions

- **Scaling Health**: 1.16.3-4.0.0
- **Silent Lib**: 1.16.2-4.8.1+61
- **Forge**: 1.16.3-34.0.7
- **Modpack**: N/A 
- **Optifine Installed**: Yes

## Expected Behavior

To have my game not crash

## Actual Behavior

Whenever mob griefing is active and a creeper explodes, the game crashes, but when it is turned off, nothing happens

## Links/Images

![2020-10-15 23-06-00](https://user-images.githubusercontent.com/72957380/96208528-bb03af00-0f3b-11eb-8d6c-d2b8efc6762a.gif)

## Steps to Reproduce the Problem

1. Turn mob griefing on
2. Approach creeper
3. Bazinga

**Comment by DatrixTHLK** [comment]
Mine is similar to this except a few differences with optifine and Forge version. (I hate to beat a dead horse though)

### Versions

- Scaling Health: 1.16.3-4.0.0+0
- Silent Lib: 1.16.2-4.8.1+61
- Forge: 1.16.3-34.1.22
- Modpack: None
- Optifine Installed: No

### **Expected Behavior**
To have my game not crash whenever creeper explodes

### **Actual Behavior**
Game crashes when creeper explodes

### **Steps to Reproduce the Problem**

1. Approach creeper
2. Bazinga
3. CTD


Crash: https://pastebin.com/6Ew8Ljr5
Debug: https://gist.github.com/DatrixTHLK/8c93b43683e0947f78ec9a80da148cf3

For me the game just quits out after trying to load the game up when I load a saved game and a new game with Scaling Health installed. Same crash log though

**Comment by Cyborgmas** [comment]
Logs would be useful (Specifically debug.log, using a paste site, not something to download). Especially without optifine. Also it works fine when mob griefing is off?

**Comment by DatrixTHLK** [comment]
For me the game just quits out after trying to load the game up when I load a saved game and a new game with Scaling Health installed. Same crash log, though, as up above.

**Comment by Cyphrx** [comment]
Yes it works perfectly fine when mob griefing is off, the following link is the crash report https://justpaste.it/388ki and this is the debug log https://file.io/x8kzRlY2olE0

**Comment by Cyborgmas** [comment]
Can not reproduce with only SH. It seems to not be SH responsible looking at the log by Datrix further but rather hunterdogtalent.
Also, if you have other mods installed putting modpack : none or N/A is not accurate ...
