### ISSUE TITLE
[Request] Config option to disable mob drops and chest loot

### ISSUE THREAD

**Issue by Menrvus** [SilentChaos512/ScalingHealth#299]
I want to use this mod only for the blight module so I don't have a use for the other items in this mod. But as far as I've tried there's no easy way to disable heart crystals, bandages, and other items that drop from mobs or spawn in chests.

**Comment by notWaterGuy12** [comment]
I would also like this, I'm currently using it in a 1.16 pack I'm working on and I'm using InControl to disable the mob drops and using AutoOreDictionary Converter to convert them into nothing. Would be really nice to be able to at least disable the crystals. instead of just deleting their functionality in the config

**Comment by Cyborgmas** [comment]
No, loot tables are intended to be modified via datapack not config options. However I will try to put optional datapacks with the mod that will accomplish that so users don't have to make them manually.
