### ISSUE TITLE
Datapacks not working at all, tanks not rendering properly, hearts reset on death after a ticking player crash.

### ISSUE THREAD

**Issue by ExiledMiner04** [SilentChaos512/ScalingHealth#365]
## Versions

- **Scaling Health**: ScalingHealth-1.17.1-5.0.1+1
- **Silent Lib**: silent-lib-1.17.1-5.0.0
- **Forge**: 1.17.1-37.0.27
- **Modpack**: N/A
- **Optifine Installed**: No

## Expected Behavior

Datapacks working properly to remove heart gain/loss based on Exp gain and other changes I make to happen.
Mob potion effects to be changed.
## Actual Behavior

I try to use the datapack and it doesn't work, tried to run it non-zipped and the screenshot and crash below happens.
Try to die in any way and you get ticking player crash and error.  I don't think gravestones installed should matter as the gravestone is placed normally even after loading back in which shows a normal death screen. Death is handled normally, just crashes between death being properly handled and respawn menu appearing (appears as soon as you load back into the world).
For the exp gain: just add exp in any way above 10 levels, and hearts are gained for every 10. Removing the exp will remove those hearts.

## Links/Images

- https://imgur.com/sFb3ZPs
- latest.log for the screenshot above: https://pastebin.pl/view/ad6e293d
- latest.log for death crash: https://pastebin.pl/view/29ac92dc
- crash for the death crash/bug: https://pastebin.pl/view/ece70695
- datapack in question: [scalinghealthchanges.zip](https://github.com/SilentChaos512/ScalingHealth/files/6956971/scalinghealthchanges.zip)

## Steps to Reproduce the Problem

1. Try to die in any way, I attack a golem and let it kill me.
2. Give yourself EXP for the heart gain problem
3. Give yourself hearts for the tanks/colors not rendering.

**Comment by Cyborgmas** [comment]
The issues with death have been fixed in 5.0.2
for health from experience, the proper way to de-activate it was to use the server config, but ive added the option to put 0 now in the correct spot in the datapack to also deactivate it.

the issue with the zip file for a datapack is that you have an extra folder in it, when you open the zip there needs to be the pack.mcmeta directly or else its not picked up. The reason you had the "safe mode" screen is because the value of 0 was invalid for `levelsPerHp`, but it is now valid in the latest version
