### ISSUE TITLE
Sync's shells and scaling health misbehaving

### ISSUE THREAD

**Issue by Ax1007** [SilentChaos512/ScalingHealth#82]
### Versions

Minecraft Version: 1.12.2
Scaling Health Version: 1.12.2-1.3.4.733
Silent Lib Version: 1.12-2.2.16-97

### Expected behavior

Dying or transferring to new shells via the Sync mod and you should retain all health upgrades.

### Actual behaviour

Respawning/transferring to new shells sometimes results in half the expected amount of hearts (22 down to 11.5 for example) that cannot be healed back unless you exit/rejoin (max HP is actually wrong). The issue can compound and result in you having less than 10 hearts. Dying WITHOUT clones, gives you the correct hearts. BONUS, going back into your main shell that previously had correct hearts shows the correct hearts UNTIL you take damage, and it resets to the wrong hearts.

### Steps to reproduce the problem

1. Create clones in the overworld
2. Die/Transfer to new shell
3. Sometimes health is lower than expected until a reset.

**Comment by SilentChaos512** [comment]
I'm seeing some slightly different behavior. The only problem is that Sync shells always start at 20 health, regardless of the player's actual max health. Max health is not changing and shells should heal up to full health over time.

There may not be anything I can do about this. I'll look through Sync's code to see if there's an event or something I can catch.

**Comment by Darkmega18** [comment]
as far as I know, Sync has this whole thing of each shell essentially being a new player. So when you create the shell it copies the data of the current player to make the clone. So the clone will have current health but any health you gain afterwards will get removed when you switch to the clone who has your old player data. They also have a bug right now where it transfers equipment and stuff due to a reaction with some mods which it's not meant to do which results in duplicated items. :V the health should heal up to what you had when you made it, but it'll probably start from 10 hearts cause thats default minecraft's full health. :V
